### ISSUE TITLE
`install_github` fails in conda environment on Linux

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-devtools-feedstock#4]
In a conda installation of R on a Linux machine, `devtools::install_github` fails because it is unable to find the correct system commands:

```
$ docker run --rm -it condaforge/linux-anvil bash
conda install -y r-base r-devtools unzip
$ R -q -e 'devtools::install_github("r-lib/devtools")'
> devtools::install_github("r-lib/devtools")
Downloading GitHub repo r-lib/devtools@master
from URL https://api.github.com/repos/r-lib/devtools/zipball/master
Installation failed: error in running command
```

One work around would be to create a conda package and host it on Anaconda Cloud, but this can be a lot of work (especially if the package has many dependencies without corresponding conda packages).  Often I want to test out the package prior to making the effort to create a conda package for it.

The problem can be solved by setting the environment variables to system commands correctly:

```
R -q
> getOption("unzip")
[1] ""
> Sys.getenv("TAR")
[1] "/bin/gtar"
> options(unzip = "/opt/conda/bin/unzip")
> Sys.setenv(TAR = "/bin/tar")
> devtools::install_github("r-lib/devtools")
```

Note in the example above, I installed unzip via conda. On a system that has `unzip`, I usually use `options(unzip = "/usr/bin/unzip")`.

Is there anyway to automatically configure these environment variables for the conda installation of R? In other words, without resorting to `.Renviron` or `.Rprofile`, which would also affect the system installation of R.

xref: https://github.com/r-lib/devtools/issues/1722 https://github.com/jupyter/docker-stacks/issues/411

**Comment by rvernica** [comment]
I can confirm the issue and the workaround.

**Comment by MaxGhenis** [comment]
The workaround (including installing unzip via conda) isn't working for me, still getting the `error in running command`.

**Comment by jdblischak** [comment]
> The workaround (including installing unzip via conda) isn't working for me, still getting the error in running command.

@MaxGhenis Could you please provide some more information to help us troubleshoot your issue? e.g.

* `conda info`
* `conda list`
* `sessionInfo()` (run inside the R executable in the conda environment)
* `getOption("unzip")`
* `Sys.getenv("TAR")`

**Comment by MaxGhenis** [comment]
@jdblischak this has all those outputs: https://gist.github.com/MaxGhenis/2a4e600da6085ee8ae9af999087a95bd

**Comment by jdblischak** [comment]
@MaxGhenis Thanks! It's not immediately apparent to me what the issue is, but a few observations:

1. You've installed Microsoft R Open ([mro-base](https://gist.github.com/MaxGhenis/2a4e600da6085ee8ae9af999087a95bd#file-gistfile1-txt-L209)). Was this your intention?
2. I couldn't find `r-devtools` anywhere in your Gist. How are you installing devtools?

**Comment by MaxGhenis** [comment]
>You've installed Microsoft R Open (mro-base). Was this your intention?

Yes, this made it easier to install some packages at some point, though I don't recall which.

>I couldn't find r-devtools anywhere in your Gist. How are you installing devtools?

Odd, I wonder if my trying `devtools::install_github("r-lib/devtools")` as in the first comment of this issue removed the `conda` installation. Here were my steps after noticing this:

1. `remove.packages("devtools")`
2. `conda install -c r r-devtools`, which said it was already installed (I didn't check if it was in `conda list` at this point)
3. `library(devtools)` in R, which says the package isn't available
4. `conda remove devtools; conda install -c r r-devtools`
5. `library(devtools)` in R works now
6. `devtools::install_github('vikjam/pwrcalc')`, the package I was initially trying to install, produces the same `Installation failed: error in running command` error

Here's my new `conda list devtools`:
```
# Name                    Version                   Build  Channel
r-devtools                1.13.4          mro343h599a50d_0    r
```

**Comment by jdblischak** [comment]
> Yes, this made it easier to install some packages at some point, though I don't recall which.

@MaxGhenis OK. Just make sure to always use MRO packages when running mro-base. Because MRO (and it's packages) are built with a different compiler, you will get errors if you try to use R packages built for r-base.

I am having trouble replicating your error. Using Ubuntu 18.04 and conda 4.5.11, I get a certificate error when trying to run `install_github` with mro-base (and I couldn't find a solution with a quick search). I used the following environment file:

```
name: test-devtools
channels:
  - ospc
  - gerrymandr
  - anaconda
  - conda-forge
  - r
  - defaults
dependencies:
  - mro-base=3.4.3=h1c2f66e_0
  - r-curl=3.1=mro343_0
  - r-devtools=1.13.4=mro343h599a50d_0
  - unzip
```

And then ran:

```
$ conda env create --file environment.yaml 
$ source activate test-devtools
$ R
> devtools::install_github("vikjam/pwrcalc")
Using GitHub PAT from envvar GITHUB_PAT
Installation failed: error setting certificate verify locations:
  CAfile: microsoft-r-cacert.pem
  CApath: none
```

However, I can confirm that using conda-forge does work. I used this environment file:

```
name: cf-devtools
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base==3.4.1
  - r-devtools
  - unzip
```

And then ran:

```
$ conda env create --file environment.yaml 
$ source activate cf-devtools
$ R
> options(unzip = Sys.which("unzip"))
> Sys.which("tar")
> devtools::install_github("vikjam/pwrcalc")
> library(pwrcalc)
```

Thus my recommendation would be to use the conda-forge channel instead of the r channel.

Also, I wasn't able to re-create the exact environment that you specified in your Gist. There were packages that no longer exist on Anaconda Cloud and some that now conflict (I gave up after a few failed attempts). To help troubleshoot your issue, I'd recommend that you create a new environment with a smaller set of packages to narrow down the potential problem.

**Comment by StevenCHowell** [comment]
I had to do the following 2 steps.

1. within R, set `options(unzip = "internal")` before installing (from [here](https://github.com/r-lib/devtools/issues/1722#issuecomment-370019534))
2. create a soft link for `/bin/gtar` pointing to '/bin/gtar` (from the [linked PR](https://github.com/jupyter/docker-stacks/pull/812#issuecomment-470987174))

    sudo ln -s /bin/tar /bin/gtar

**Comment by liutiming** [comment]
I am curious if this has been resolved? So far the only way still seems to be the workaround

**Comment by jdblischak** [comment]
> I am curious if this has been resolved? So far the only way still seems to be the workaround

@liutiming The issue should be resolved. I am able to use `devtools::install_github()` without the workaround. Are you using R installed from the conda-forge channel? Could you please share the output of `conda list` and `conda info`?

**Comment by liutiming** [comment]
@jdblischak yes I was using R installed from conda but this is not urgent :)

**Comment by jdblischak** [comment]
> yes I was using R installed from conda but this is not urgent :)

@liutiming We can't help you unless you provide more information on your setup. The problem is solved if you install R and devtools from the conda-forge channel.

```
conda install -c conda-forge r-base r-devtools
```

If you need help troubleshooting, please include the output of `conda info` and `conda list`.
